const POSITION_DOTS = '3vh';
const SLIDER_IMAGES_OPACITY = '0.6';
const FONT_WEIGHT_NAVIGATION_ACTIVE = 800;
const MAIN_TITLE_FEATURE_FONT_SIZE = '6vh';
const POSITION_SLIDER_CONTENT = '10vw';

export {
  POSITION_DOTS,
  SLIDER_IMAGES_OPACITY,
  FONT_WEIGHT_NAVIGATION_ACTIVE,
  MAIN_TITLE_FEATURE_FONT_SIZE,
  POSITION_SLIDER_CONTENT,
};
